# Generated by Django 5.1.7 on 2025-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_floor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='floor_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
