# Generated by Django 5.1.7 on 2025-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_blog_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
