# Generated by Django 5.1.7 on 2025-03-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_blog_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='deadline',
        ),
    ]
